name: CI

# Run on push, pull request, or manual activation
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs Python 3
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      
      # Installs necessary libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Runs the python tests
      - name: Run tests
        run: python test.py
